//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventOrganizeDomainClasses
{ 
    using System;
    using System.Collections.Generic;

    public partial class Attendant
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> EventId { get; set; }

        public virtual Event Event { get; set; }
        public virtual cls_Role cls_Role { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
