//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventOrganizeDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using EventOrganizeDomainClasses;

    public partial class EventOrganizingEntities : DbContext
    {
        public EventOrganizingEntities()
            : base("name=EventOrganizingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendant> Attendants { get; set; }
        public virtual DbSet<cls_Place> cls_Place { get; set; }
        public virtual DbSet<cls_Resources> cls_Resources { get; set; }
        public virtual DbSet<cls_Role> cls_Role { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
    
        
        
    
   
    }
}
